### PR TITLE
Adding VirtualBox 5.0.0 support.

### PR DESCRIPTION
**Pull request by TheIndifferent**
Used 4.3 as a base, only line 187 was modified because of VBox API changes.

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
Looks good from what I see in this PR and in files for other VirtualBox versions. BTW I have no background in VBox APIs, so it's just a top-level review. If VirtualBox 5 works correctly, makes sense to go forward and to release the change.

**Comment by samrocketman** [comment]
You added binary jar files to your pull request.

* lib/org/virtualbox/vboxws-50/5.0.0/vboxws-50-5.0.0-sources.jar 
* lib/org/virtualbox/vboxws-50/5.0.0/vboxws-50-5.0.0.jar

That's the wrong way to go about it.  You should add jar file dependencies to the root `pom.xml` rather than committing them directly.  Fix the binaries, update `pom.xml`, and squash your changes.

**Comment by samrocketman** [comment]
oomf I just realized there's a lot of jars committed already in the same form that you're proposing for this pull request.  So I guess it's the norm for this plugin.  There's got to be a better way but it would involve a deeper rewrite than what you're proposing.

**Comment by sven-ke** [comment]
Is there a reason, why the VBox 5.0.x changes are not merged to master?
Currently I built my own version from [dbroady1](https://github.com/jenkinsci/virtualbox-plugin/issues/12) and it seems to work so far, but I'd prefer to use an "officially" supported version.

**Comment by samrocketman** [comment]
I can reach out to the maintainer and ask them if they're willing to hand off the project to me.

**Comment by samrocketman** [comment]
I have reached out to the most recent maintainer @hgomez and he said I can take over as the maintainer for this project.  I'll start by looking at and potentially merging this PR.  After that, I'll look over other PRs.

Here's a screenshot of our email conversation.

screen shot 2016-12-22 at 11 23 11 am

**Comment by furduialex** [comment]
Any news when the merge with the master will be done ?

**Comment by joaquin386** [comment]
Anything on the support to the 5.0 and 5.1?

**Comment by samrocketman** [comment]
The handoff to me is complete per my comment above.  I've just been busy with other priorities (in projects and otherwise).  In the mean time, you can build this yourself and try it out.

```
git clone git@github.com:jenkinsci/virtualbox-plugin.git
cd virtualbox-plugin/
git ls-remote | grep '10'
git fetch origin refs/pull/10/head
git checkout FETCH_HEAD
JAVA_HOME=/path/to/jdk8 mvn package
```

The plugin will be in `./plugin/target/virtualbox.hpi`.

**Comment by joaquin386** [comment]
The connection is working fine with 5.0.X

**Comment by lifeofguenter** [comment]
Will this also work with Virtualbox 5.1.x ?

**Comment by jcormier** [comment]
Seems like there are other peoples branches which have added 5.1 support.
https://github.com/swurzinger/virtualbox-plugin/commits/master

**Pull request closed without merging**
